# Generated by Django 5.2.7 on 2025-12-02 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.IntegerField(unique=True, verbose_name='Member Number')),
                ('secret_code', models.CharField(max_length=8, unique=True, verbose_name='Secret Code')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('payment_date', models.DateField()),
                ('is_registered', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Number',
                'verbose_name_plural': 'Member Numbers',
                'ordering': ['member_number'],
            },
        ),
    ]
