# Generated by Django 5.2.7 on 2025-12-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_alumniprofile_facebook_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernumber',
            name='first_name',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='membernumber',
            name='last_name',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
