# Generated by Django 5.2.7 on 2025-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_membernumber_first_name_membernumber_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernumber',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='membernumber',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='First Name'),
        ),
    ]
