# Generated by Django 5.2.7 on 2025-12-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_membernumber_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cause', models.CharField(choices=[('general', 'General Fund'), ('scholarship', 'Scholarship Fund'), ('infrastructure', 'School Infrastructure'), ('sports', 'Sports & Athletics'), ('library', 'Library & Resources'), ('emergency', 'Emergency Relief Fund')], default='general', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Optional message or dedication')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
